export const ActionsTypes = {
    SET_MOVİES : 'SET_MOVİES',
    SET_MOVİES_LOADİNG: 'SET_MOVİES_LOADİNG_',
    SET_MOVİES_ERROR: 'SET_MOVİES_ERROR',
  
  
  
    SET_GENRES: 'SET_GENRES',
    SET_GENRES_LOADİNG :'SET_GENRES_LOADİNG',
    SET_GENRES_ERROR:'SET_GENRES_ERROR',
  };
  